export {
  classifyStrings,
  expectedRingsMask,
  matchChord,
  verifyChord,
  aggregateChromaFrames,
  verifierThresholdFor,
  type ChromaAggregateResult,
  type ChromaFrame,
  type ChordMatchResult,
  type ChordStringClass,
  type ChordVerifierResult,
  type ChordVerifierStatus,
  type ChordVerifierThreshold,
} from "@/audio/chord-detection";
